#!/bin/bash
#########################################
# HOMESEER (V4) LINUX - INSTALL SCRIPT
#########################################
#
#  curl -ssL https://homeseer.sh/install | sudo bash
#

# download and install the HOMESEER.SH GPG public key
echo ====================================================
echo INSTALLING HOMESEER.SH GPG PUBLIC KEY
echo ====================================================
curl -ssL https://homeseer.sh/homeseer.gpg -o /etc/apt/keyrings/homeseer.key
gpg --yes -o /etc/apt/keyrings/homeseer.gpg --dearmor /etc/apt/keyrings/homeseer.key
rm /etc/apt/keyrings/homeseer.key
chown root:root /etc/apt/keyrings/homeseer.gpg
chmod ugo+r /etc/apt/keyrings/homeseer.gpg
chmod go-w /etc/apt/keyrings/homeseer.gpg

# download and install the HOMESEER.SH apt repository list
echo ====================================================
echo ADDING HOMESEER.SH APT REPOSITORY
echo ====================================================
sudo curl -sSL https://homeseer.sh/v4/homeseer.list --output /etc/apt/sources.list.d/homeseer.list

# update the apt package list
echo ====================================================
echo UPDATING APT REPOSITORIES
echo ====================================================
apt-get update -o Dir::Etc::sourcelist="sources.list.d/homeseer.list"  -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

# install prerequisites
echo ====================================================
echo INSTALLING PREREQUSITES
echo ====================================================
apt-get update
apt-get install --yes mono-complete mono-devel mono-vbnc flite chromium-browser aha ffmpeg alsa-base alsa-utils tmux curl wget nano
apt-get remove --yes brltty

# download and install HomeSeer debian package
echo ====================================================
echo INSTALLING HOMESEER
echo ====================================================
apt-get install homeseer

echo ====================================================
echo HOMESEER INSTALLATION COMPLETE
echo ====================================================
echo
echo The Homeseer installation files are located at:
echo   /opt/homeseer
echo
echo Please see https://homeseer.sh for more information.
echo
