#!/bin/bash
#########################################
# HOMESEER (V4) LINUX - UNINSTALL SCRIPT
#########################################
#
#  curl -ssL https://homeseer.dev/uninstall | sudo bash
#

# uninstall homeseer debian package
echo ====================================================
echo UNINSTALLING Pi4J
echo ====================================================
apt-get remove homeseer -y

# remove homeseer from apt repository list
echo ====================================================
echo REMOVING HOMESEER.DEV APT REPOSITORY
echo ====================================================
rm /etc/apt/sources.list.d/homeseer.list

# remove the HOMESEER.DEV GPG public key
echo ====================================================
echo REMOVING HOMESEER.DEV GPG PUBLIC KEY
echo ====================================================
apt-key del team@homeseer.dev

# update the apt package list
echo ====================================================
echo UPDATING APT REPOSITORIES
echo ====================================================
apt-get update

echo ====================================================
echo HOMESEER (V4) UNINSTALL COMPLETE
echo ====================================================
