#!/bin/bash
#########################################
# HOMESEER (V4) LINUX - UNINSTALL SCRIPT
#########################################
#
#  curl -ssL https://homeseer.sh/uninstall | sudo bash
#

# uninstall homeseer debian package
echo ====================================================
echo UNINSTALLING HOMESEER
echo ====================================================
apt-get remove homeseer -y

# remove homeseer from apt repository list
echo ====================================================
echo REMOVING HOMESEER.SH APT REPOSITORY
echo ====================================================
rm /etc/apt/sources.list.d/homeseer.list

# remove the HOMESEER.SH GPG public key
echo ====================================================
echo REMOVING HOMESEER.SH GPG PUBLIC KEY
echo ====================================================
apt-key del team@homeseer.sh

# update the apt package list
echo ====================================================
echo UPDATING APT REPOSITORIES
echo ====================================================
apt-get update

echo ====================================================
echo HOMESEER (V4) UNINSTALL COMPLETE
echo ====================================================
